//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDbAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MesDbEntities : DbContext
    {
        public MesDbEntities()
            : base("name=MesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmMe> AlarmMes { get; set; }
        public virtual DbSet<BreakerMe> BreakerMes { get; set; }
        public virtual DbSet<ElectricityMeterMe> ElectricityMeterMes { get; set; }
    }
}
