//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDbAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MesDbEntities : DbContext
    {
        public MesDbEntities()
            : base("name=MesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmMe> AlarmMes { get; set; }
        public virtual DbSet<BreakerMe> BreakerMes { get; set; }
        public virtual DbSet<ElectricityMeterMe> ElectricityMeterMes { get; set; }
    
        public virtual ObjectResult<AlarmHistoryFromTo_Result> AlarmHistoryFromTo(Nullable<System.DateTime> param1, Nullable<System.DateTime> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(System.DateTime));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AlarmHistoryFromTo_Result>("AlarmHistoryFromTo", param1Parameter, param2Parameter);
        }
    }
}
